name: pokedex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  poke_client:
    path: packages/poke_client
  bloc: ^7.0.0
  json_annotation: ^4.8.0
  equatable: ^2.0.3
  google_fonts: ^2.1.0
  flutter_bloc: ^7.3.3
  build_runner: ^2.1.4
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15

flutter_icons:
  image_path: "assets/pokeball.png"
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/

