name: poke_client
description: The interface and models for an API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
